# Copyright 2025 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import unittest
import re
import os
import csv


class TestGoldenSet(unittest.TestCase):
    """
    Evaluates the 'Executive Report' (The communicative output).
    """

    def setUp(self):
        # Logic to load the report generated by the agent
        self.report_path = "./gdrive_sync/Executive_Summary_H100_Crisis.txt"

        # Fail if report wasn't generated (Connectivity Check)
        if not os.path.exists(self.report_path):
            self.fail("CRITICAL: Report not found. Connectivity to GDrive failed.")

        with open(self.report_path, "r") as f:
            self.content = f.read()

    def test_inventory_discovery(self):
        """Did it find the 300 units in LEGACY_INV_MAIN_V2 with LOC_BIN_HEX='55'?"""
        has_count = "300" in self.content
        has_loc = "55" in self.content or "Quarantine" in self.content

        self.assertTrue(has_count, "FAIL: Report did not mention finding 300 units.")
        self.assertTrue(
            has_loc, "FAIL: Report did not identify the Quarantine/Hex-55 location."
        )

    def test_legal_justification(self):
        """Did it cite Clause 7.B from the Nvidia contract?"""
        # We look for the specific clause citation that allows breaking exclusivity
        has_clause = "7.B" in self.content or "Force Majeure" in self.content

        self.assertTrue(
            has_clause,
            "FAIL: Legal justification (Clause 7.B / Force Majeure) missing.",
        )

    def test_procurement_recommendation(self):
        """Did it recommend buying ONLY 200 units from the spot market?"""
        # Regex to find 'Buy X' or 'Purchase X'
        buy_matches = re.findall(
            r"(?:buy|purchase|procure)\s+(\d+)", self.content.lower()
        )

        # Check if '200' is among the recommended numbers
        is_correct_amount = any(m == "200" for m in buy_matches)

        self.assertTrue(
            is_correct_amount, "FAIL: Did not recommend buying exactly 200 units."
        )


class TestProcurementTracker(unittest.TestCase):
    """
    Evaluates the 'System of Record' (The operational state).
    This is the new Pivot requirement.
    """

    def setUp(self):
        self.tracker_path = "./workspace/procurement_tracker.csv"

        if not os.path.exists(self.tracker_path):
            self.fail(
                "CRITICAL: Procurement Tracker CSV not found. Agent failed to maintain state."
            )

    def test_tracker_integrity(self):
        """Validates the CSV structure and content."""
        with open(self.tracker_path, "r") as f:
            reader = csv.reader(f)
            rows = list(reader)

        # 1. Check Header
        header = [h.strip().lower() for h in rows[0]]
        expected_cols = ["timestamp", "source", "quantity", "status", "notes"]
        # Loose check if crucial columns exist
        self.assertIn("source", header, "FAIL: CSV missing 'source' column")
        self.assertIn("quantity", header, "FAIL: CSV missing 'quantity' column")

        # 2. Check for Internal Stock Release (300 units)
        # We iterate through rows to find the specific transaction
        found_internal = False
        for row in rows:
            # Join row to string for easier searching or check specific indices if strictly formatted
            row_str = str(row).lower()
            if "300" in row_str and ("internal" in row_str or "quarantine" in row_str):
                found_internal = True
                break

        self.assertTrue(
            found_internal,
            "FAIL: Tracker does not record the release of 300 internal units.",
        )

        # 3. Check for Spot Market Purchase (200 units)
        found_spot = False
        for row in rows:
            row_str = str(row).lower()
            if "200" in row_str and ("spot" in row_str or "market" in row_str):
                found_spot = True
                break

        self.assertTrue(
            found_spot, "FAIL: Tracker does not record the purchase of 200 spot units."
        )


if __name__ == "__main__":
    unittest.main()
